import type { Metadata } from 'next'
import './globals.css'
import StoreProvider from '@/context/StoreProvider'


export const metadata: Metadata = {
  title: 'www.codexec.com',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
        {children}
        </StoreProvider>
        </body>
    </html>
  )
}
